// Generates responsive WebP variants for every original photo and a manifest
// (intrinsic sizes) used by the front-end to build srcset + width/height.
//
//   cd scripts && npm install && npm run images
//
// Output:
//   assets/img/optimized/<folder>/<stem>-<480|960|1600>.webp
//   assets/img/og-cover.jpg (1200x630, social previews)
//   assets/js/media-manifest.js
//
// Incremental: files whose outputs are newer than the source are skipped.

import { readdir, stat, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const IMG_DIR = path.join(ROOT, 'assets/img');
const OUT_DIR = path.join(IMG_DIR, 'optimized');
const FOLDERS = ['cile', 'china', 'scotland', 'sri_lanka', 'thailandia', 'usa', 'other'];
const WIDTHS = [480, 960, 1600];
const OG_SOURCE = 'usa/IMG_1018.JPG';

const sanitize = (stem) => stem.replace(/[^A-Za-z0-9_-]+/g, '-');

async function mtime(file) {
  try {
    return (await stat(file)).mtimeMs;
  } catch {
    return 0;
  }
}

async function processImage(folder, file) {
  const src = path.join(IMG_DIR, folder, file);
  const stem = sanitize(file.replace(/\.[^.]+$/, ''));
  const outBase = path.join(OUT_DIR, folder, stem);
  const srcTime = await mtime(src);

  // EXIF orientation 5-8 means the stored pixels are rotated 90°.
  const { width: rawW, height: rawH, orientation } = await sharp(src).metadata();
  const rotated = orientation >= 5;
  const meta = { width: rotated ? rawH : rawW, height: rotated ? rawW : rawH };

  for (const width of WIDTHS) {
    const out = `${outBase}-${width}.webp`;
    if ((await mtime(out)) > srcTime) continue;
    await sharp(src)
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: width <= 480 ? 70 : 74, effort: 5 })
      .toFile(out);
  }

  return [`${folder}/${file}`, `${folder}/${stem}`, meta.width, meta.height];
}

async function main() {
  const entries = [];

  for (const folder of FOLDERS) {
    await mkdir(path.join(OUT_DIR, folder), { recursive: true });
    const files = (await readdir(path.join(IMG_DIR, folder)))
      .filter((f) => /\.(jpe?g|png)$/i.test(f))
      .sort();

    // Small pool: sharp is already multi-threaded internally.
    const queue = [...files];
    const workers = Array.from({ length: 3 }, async () => {
      while (queue.length) {
        const file = queue.shift();
        try {
          entries.push(await processImage(folder, file));
          process.stdout.write('.');
        } catch (error) {
          console.error(`\nFAILED ${folder}/${file}: ${error.message}`);
        }
      }
    });
    await Promise.all(workers);
    console.log(` ${folder} (${files.length})`);
  }

  entries.sort((a, b) => a[0].localeCompare(b[0]));
  const manifest = Object.fromEntries(entries.map(([key, base, w, h]) => [key, [base, w, h]]));

  await writeFile(
    path.join(ROOT, 'assets/js/media-manifest.js'),
    '// Generated by scripts/optimize-images.mjs — do not edit by hand.\n' +
    `// key: original path under assets/img → [optimized base, width, height]\n` +
    `window.travelMediaWidths = ${JSON.stringify(WIDTHS)};\n` +
    `window.travelMedia = ${JSON.stringify(manifest)};\n`
  );

  await sharp(path.join(IMG_DIR, OG_SOURCE))
    .rotate()
    .resize({ width: 1200, height: 630, fit: 'cover', position: 'attention' })
    .jpeg({ quality: 78, mozjpeg: true })
    .toFile(path.join(IMG_DIR, 'og-cover.jpg'));

  console.log(`Done: ${entries.length} images, manifest + og-cover written.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
